### ISSUE TITLE
Access to 10x multiome dataset

### ISSUE THREAD

**Issue by MoLuLuMo** [kimmo1019/scDEC#3]
I cannot access the cloud server mentioned in https://github.com/kimmo1019/scDEC/wiki/PBMC10k. 

Besides, I cannot find cell-type label that were annotated by the 10x Genomics R&D team. Could you provide the cell type annotation information?

Thanks

**Comment by kimmo1019** [comment]
Thanks for asking, we apologized that the previous cloud server is not working.
You can find the annotated label at https://drive.google.com/file/d/1LdbsWe096DSeMcOUlZol7v810qgcBaS9/view?usp=sharing

**Comment by MoLuLuMo** [comment]
Thanks for providing the annotation label list.
